### ISSUE TITLE
Instructions for running multiplayer mode over internet

### ISSUE THREAD

**Issue by frantic** [jimpurbrick/pairs#1]
Would be really cool to provide some instructions on how to share and run this game from multiple headsets over internet. Ideally users would get a public URL that they can share with friends. Opening that URL will open Carmel browser.

Looks like the game currently runs 2 servers: React Packager bundler server and `wsrelay` to communicate between instances. The way I see we could make this work is following (but lmk if I'm missing something):

1. Build a static bundle with `npm run bundle`
2. Write a small custom nodejs server that can serve static html and relay websocket connections
3. Use [`ngrok`](https://ngrok.com/) or similar to expose that server to the outer world.

cc @mikearmstrong001, @andrewimm

**Comment by frantic** [comment]
Re: (2) I hacked together a small package that acts as static http server + websocket relay: [buzz-chamber](https://github.com/frantic/buzz-chamber).

**Comment by mikearmstrong001** [comment]
This was discussed offline with @jimpurbrick mid last week, I'll echo here.

One oversight that is being resolved is that I didn't expose the initial `windows.location` to `ReactVRConstants`. When available this will allow the  url and query params to be inspected.

A fix for this will roll out within the next few days and will allow the WebSocket connection to connect to the same ip address as the browse to location.

**Comment by jimpurbrick** [comment]
@frantic you're correct, there are 2 servers here and your plan would work to allow people to play over the internet. As mike points out, once the websocket address is configurable via the query string a potentially the client can be served as a static site allowing a vanilla wsrelay to be used for the websocket piece. One of the next steps is to make the server smarter to allow for hidden state and avoid broadcasting initial state to older clients, so a custom node app is likely in the future anyway.

**Comment by jimpurbrick** [comment]
Instructions added in f0e331355c263a3ee4dd11bc30853178963d99a0. Once ReactVR supports query string parameters the application can be served from gh-pages and the relay address passed via the URL to avoid code changes and running an ngrok relay to serve the application.

**Comment by frantic** [comment]
Awesome, thanks @jimpurbrick!
